[versions]
assertj = "3.24.2"
junitJupiter = "5.9.3"

[libraries]
junit5 = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junitJupiter" }
assertj = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }

[plugins]
nebula-release = { id = "nebula.release", version = "17.2.2" }
